### ISSUE TITLE
calculate doesn't work on Lacona 1.1.1

### ISSUE THREAD

**Issue by rbeeger** [laconalabs/LaconaApp#145]
When I enter 
`calculate 34+23`
Lacona proposes 
`search calculate 34+23 on search engine`

This used to work in 1.0.3.
When I start to type `calcu` Lacona proposes `calculate expression` but recognition of the expression seems to be broken.

**Comment by brandonhorst** [comment]
![image](https://cloud.githubusercontent.com/assets/1938545/20644478/8a2e5ea8-b403-11e6-9e54-c70edf815308.png)

Works for me. Could you send me a copy of `~/Library/Logs/Lacona/app.log`, if possible?

**Comment by rbeeger** [comment]
GitHub doesn't know log files. So since it's not overly long, here's its content
```
{ Error: stdout maxBuffer exceeded
    at Socket.<anonymous> (child_process.js:255:14)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:172:18)
    at Socket.Readable.push (_stream_readable.js:130:10)
    at Pipe.onread (net.js:535:20) cmd: 'top' }
stdout: undefined
stderr: undefined
Error Parsing TypeError: Path must be a string. Received null
    at assertPath (path.js:7:11)
    at basename (path.js:1355:5)
    at _lodash2.default.chain.filter.map (/Applications/Lacona.app/Contents/Resources/Node/node_modules/lacona-osx/lib-node/spotlight-fs.js:44:30)
    at arrayMap (/Applications/Lacona.app/Contents/Resources/Node/node_modules/lodash/lodash.js:643:23)
    at Function.map (/Applications/Lacona.app/Contents/Resources/Node/node_modules/lodash/lodash.js:9418:14)
    at interceptor (/Applications/Lacona.app/Contents/Resources/Node/node_modules/lodash/lodash.js:16781:35)
    at thru (/Applications/Lacona.app/Contents/Resources/Node/node_modules/lodash/lodash.js:8647:14)
    at /Applications/Lacona.app/Contents/Resources/Node/node_modules/lodash/lodash.js:4292:28
    at arrayReduce (/Applications/Lacona.app/Contents/Resources/Node/node_modules/lodash/lodash.js:687:21)
    at baseWrapperValue (/Applications/Lacona.app/Contents/Resources/Node/node_modules/lodash/lodash.js:4291:14)
    at LazyWrapper.lazyValue [as value] (/Applications/Lacona.app/Contents/Resources/Node/node_modules/lodash/lodash.js:1832:16)
Error Parsing TypeError: Path must be a string. Received null
    at assertPath (path.js:7:11)
    at basename (path.js:1355:5)
    at _lodash2.default.chain.filter.map (/Applications/Lacona.app/Contents/Resources/Node/node_modules/lacona-osx/lib-node/spotlight-fs.js:44:30)
    at arrayMap (/Applications/Lacona.app/Contents/Resources/Node/node_modules/lodash/lodash.js:643:23)
    at Function.map (/Applications/Lacona.app/Contents/Resources/Node/node_modules/lodash/lodash.js:9418:14)
    at interceptor (/Applications/Lacona.app/Contents/Resources/Node/node_modules/lodash/lodash.js:16781:35)
    at thru (/Applications/Lacona.app/Contents/Resources/Node/node_modules/lodash/lodash.js:8647:14)
    at /Applications/Lacona.app/Contents/Resources/Node/node_modules/lodash/lodash.js:4292:28
    at arrayReduce (/Applications/Lacona.app/Contents/Resources/Node/node_modules/lodash/lodash.js:687:21)
    at baseWrapperValue (/Applications/Lacona.app/Contents/Resources/Node/node_modules/lodash/lodash.js:4291:14)
    at LazyWrapper.lazyValue [as value] (/Applications/Lacona.app/Contents/Resources/Node/node_modules/lodash/lodash.js:1832:16)
/Users/robertbeeger/Library/Application Support/Lacona/Addons/node_modules/rxjs/observable/PromiseObservable.js:76
                    root_1.root.setTimeout(function () { throw err; });
                                                         ^

Error: ENOENT: no such file or directory, open '/var/folders/fn/b9n9rks5287ft2fb7ddlzq780000gn/T/.lacona-timer.pid'
    at Error (native)
/Users/robertbeeger/Library/Application Support/Lacona/Addons/node_modules/rxjs/observable/PromiseObservable.js:76
                    root_1.root.setTimeout(function () { throw err; });
                                                         ^

Error: ENOENT: no such file or directory, open '/var/folders/fn/b9n9rks5287ft2fb7ddlzq780000gn/T/.lacona-timer.pid'
    at Error (native)
(node:16228) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'general' of undefined
(node:16228) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
/Users/robertbeeger/Library/Application Support/Lacona/Addons/node_modules/rxjs/observable/PromiseObservable.js:76
                    root_1.root.setTimeout(function () { throw err; });
                                                         ^

Error: ENOENT: no such file or directory, open '/var/folders/fn/b9n9rks5287ft2fb7ddlzq780000gn/T/.lacona-timer.pid'
/Users/robertbeeger/Library/Application Support/Lacona/Addons/node_modules/rxjs/observable/PromiseObservable.js:76
                    root_1.root.setTimeout(function () { throw err; });
                                                         ^

Error: ENOENT: no such file or directory, open '/var/folders/fn/b9n9rks5287ft2fb7ddlzq780000gn/T/.lacona-timer.pid'
/Users/robertbeeger/Library/Application Support/Lacona/Addons/node_modules/rxjs/observable/PromiseObservable.js:76
                    root_1.root.setTimeout(function () { throw err; });
                                                         ^

Error: ENOENT: no such file or directory, open '/var/folders/fn/b9n9rks5287ft2fb7ddlzq780000gn/T/.lacona-timer.pid'
/Users/robertbeeger/Library/Application Support/Lacona/Addons/node_modules/rxjs/observable/PromiseObservable.js:76
                    root_1.root.setTimeout(function () { throw err; });
                                                         ^

Error: ENOENT: no such file or directory, open '/var/folders/fn/b9n9rks5287ft2fb7ddlzq780000gn/T/.lacona-timer.pid'
/Users/robertbeeger/Library/Application Support/Lacona/Addons/node_modules/rxjs/observable/PromiseObservable.js:76
                    root_1.root.setTimeout(function () { throw err; });
                                                         ^

Error: ENOENT: no such file or directory, open '/var/folders/fn/b9n9rks5287ft2fb7ddlzq780000gn/T/.lacona-timer.pid'
/Users/robertbeeger/Library/Application Support/Lacona/Addons/node_modules/rxjs/observable/PromiseObservable.js:76
                    root_1.root.setTimeout(function () { throw err; });
                                                         ^

Error: ENOENT: no such file or directory, open '/var/folders/fn/b9n9rks5287ft2fb7ddlzq780000gn/T/.lacona-timer.pid'
/Users/robertbeeger/Library/Application Support/Lacona/Addons/node_modules/rxjs/observable/PromiseObservable.js:76
                    root_1.root.setTimeout(function () { throw err; });
                                                         ^

Error: ENOENT: no such file or directory, open '/var/folders/fn/b9n9rks5287ft2fb7ddlzq780000gn/T/.lacona-timer.pid'
/Users/robertbeeger/Library/Application Support/Lacona/Addons/node_modules/rxjs/observable/PromiseObservable.js:76
                    root_1.root.setTimeout(function () { throw err; });
                                                         ^

Error: ENOENT: no such file or directory, open '/var/folders/fn/b9n9rks5287ft2fb7ddlzq780000gn/T/.lacona-timer.pid'

```

**Comment by brandonhorst** [comment]
There are no problems with the Calculate functionality reported. I don't know what the issue would be unless it was a problem with the underlying math functionality.

Just to confirm, you do have "calculate" enabled in the preferences, right? 
![image](https://cloud.githubusercontent.com/assets/1938545/20890228/1cfa8578-bad4-11e6-9113-c2b3e38be184.png)

**Comment by rbeeger** [comment]
Yes, it's enabled. Funny thing
`calculate 23+42`
doesn't work.
`23+42` works and executes `calculate 23+42`

**Comment by rbeeger** [comment]
Seems to be connected with https://github.com/laconalabs/LaconaApp/issues/149 .
I had an outdated version of "Timers and Alarms". After removing it and installing it again, calculate works again.

**Comment by brandonhorst** [comment]
Closing. Will track updates in #149. Thanks for reporting!
